/** Textos do messages.properties (PT) */
export const t = {
  footer: "GameTests Platform. Todos os direitos reservados.",
  header: {
    title: "GameTests Platform",
    subtitle: "Sistema de Gerenciamento de Testes",
    adminTitle: "Painel do Administrador",
    adminSubtitle: "GameTests Management Suite",
    testerTitle: "Painel do Testador",
    testerSubtitle: "Gerencie suas sessões de teste",
    logout: "Sair",
  },
  home: {
    welcome: "Bem-vindo(a) à Nossa Plataforma!",
    welcomeSubtitle:
      "Explore um repositório completo de estratégias de teste, projetado para ajudar você a melhorar a qualidade e a eficiência dos seus projetos de software.",
    adminWelcome: "Bem-vindo(a) de volta!",
    adminSubtitle: "Utilize os painéis abaixo para gerenciar os rescursos do sistema.",
    testerWelcome: "Bem-vindo(a) ao seu painel!",
    testerSubtitle:
      "Aqui você pode iniciar novas sessões de teste, acompanhar seu progresso e visualizar estratégias.",
    strategyCardTitle: "Estratégias de Teste",
    strategyCardDesc: "Veja informações sobre as estratégias.",
    strategyView: "Visualizar Estratégias",
    projectTitle: "Gerenciar Projetos",
    projectDesc: "Crie novos projetos, edite informações existentes ou remova projetos obsoletos.",
    projectBtn: "Listar/Gerenciar Projetos",
    strategyAdminTitle: "Gerenciar Estratégias",
    strategyAdminDesc:
      "Defina e refine as estratégias de teste que podem ser aplicadas nas sessões.",
    strategyListBtn: "Listar/Gerenciar Estratégias",
    strategyCreate: "Criar Estratégia Nova",
    usersTitle: "Gerenciar Usuários",
    usersDesc: "Administre contas de usuário, atribua papéis e monitore atividades.",
    usersAdmins: "Gerenciar Administradores",
    usersTesters: "Gerenciar Testadores",
    sessionsTitle: "Gerenciar Sessões de Teste",
    sessionsDesc: "Visualize todas as sessões de teste, edite detalhes ou remova sessões.",
    sessionsBtn: "Listar Todas as Sessões",
    testerSessionsBtn: "Iniciar Nova Sessão de Teste",
    projectViewTitle: "Visualizar Projetos",
    projectViewDesc: "Navegue pelos projetos e veja informações detalhadas sobre eles.",
    projectViewBtn: "Listar Projetos",
  },
  login: {
    title: "Login",
    emailPh: "Digite seu e-mail",
    passwordPh: "Digite sua senha",
    guest: "Não possui uma conta?",
    guestLink: "Entrar como visitante",
  },
  projects: {
    pageTitle: "Gerenciar Projetos",
    orderBy: "Ordenar por:",
    orderName: "Nome (A-Z)",
    orderDate: "Data de Criação",
    newBtn: "+ Novo Projeto",
    tableName: "Nome",
    tableDesc: "Descrição",
    tableDate: "Data de Criação",
    tableAction: "Ações",
    filterBy: "Filtrar por",
    filterAll: "Todos",
    filterMine: "Meus projetos",
    modalNew: "Novo projeto",
    modalEdit: "Editar Projeto",
    members: "Membros Permitidos:",
    save: "Salvar",
    deleteTitle: "Confirmar Exclusão",
    deleteDesc: "Deseja realmente excluir esse projeto?",
    deleteConfirm: "Confirmar",
    deleteCancel: "Cancelar",
    seeSessions: "Ver Sessões",
    edit: "Editar",
    delete: "Deletar",
    name: "Nome:",
    description: "Descrição:",
  },
  sessions: {
    pageTitle: "Gerenciar Sessões de Teste",
    newBtn: "+ Nova Sessão",
    tableProject: "Projeto",
    tableTester: "Testador",
    tableStrategy: "Estratégia",
    tableStatus: "Status",
    tableActions: "Ações",
    details: "Detalhes",
    delete: "Deletar",
  },
  sessionDetails: {
    title: "Detalhes da Sessão",
    back: "Voltar para Lista",
    info: "Informações da Sessão",
    id: "ID da Sessão:",
    project: "Nome do Projeto:",
    time: "Duração Planejada:",
    description: "Descrição/Objetivos:",
    date: "Data de Criação:",
    start: "Data/Hora de Início:",
    end: "Data/Hora Fim:",
    pending: "Pendente",
    strategy: "Detalhes da Estratégia Associada",
    name: "Nome:",
    bugs: "Bugs Relatados",
    newBug: "Descreva o novo bug:",
    addBug: "Adicionar Bug",
    actions: "Ações da Sessão",
    begin: "Iniciar Sessão",
    finish: "Finalizar Sessão",
    completed: "Esta sessão foi finalizada e não pode mais ser modificada.",
  },
  strategies: {
    pageTitle: "Gerenciar Estratégias",
    listTitle: "Estratégias",
    back: "Voltar",
    create: "Criar Estratégia",
    tableName: "Nome",
    tableDesc: "Descrição",
    tableEx: "Exemplos",
    tableTip: "Dicas",
    tableImg: "Imagens",
    tableDel: "Deletar",
    empty: "Nenhuma estratégia cadastrada.",
    gallery: "Galeria de Imagens da Estratégia",
    createTitle: "Cadastrar Nova Estratégia",
    createBack: "Voltar para listagem",
    createName: "Nome:",
    createDesc: "Descrição:",
    createEx: "Exemplos:",
    createTip: "Dicas:",
    createImages:
      "Imagens para auxiliar a exemplificação (opcional - Se quiser adicionar múltiplas imagens, selecione-as de uma vez):",
    createSubmit: "Cadastrar Estratégia",
  },
  admins: {
    pageTitle: "Gerenciar Administradores",
    newBtn: "+ Novo Administrador",
    tableName: "Nome",
    tableEmail: "E-mail",
    tableActions: "Ações",
    save: "Salvar",
    passwordTip: "Deixe em branco para manter a senha atual ao editar.",
    deleteTitle: "Confirmar Exclusão?",
  },
  testers: {
    pageTitle: "Gerenciar Testadores",
    newBtn: "+ Novo Testador",
  },
} as const;
